### PR TITLE
Convert recipe to noarch and enable build for Windows

### PR DESCRIPTION
**Pull request by n-elie**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Is there a reason that building on Windows is disabled?
I may be wrong but I think py2cytoscape is a pure Python package, so Windows build should not cause any problem.
This PR enable windows build and convert this recipe to noarch

### CODE REVIEW

**Comment by n-elie** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Are all the dependencies (igraph) actually available for windows from
conda-forge? I haven't looked in a while.

Also, to claim the package is not py2, you'd put a pin on the python deps
and remove the skip altogether.

**Comment by n-elie** [comment]
Yes it is: https://anaconda.org/conda-forge/python-igraph
Thanks for the hint to fix the selector error

**Comment by bollwyvl** [comment]
Ah, very good. I'll review this the next chance I get.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@n-elie thanks again for this: please excuse my direct commits, but it's a bit of an intricate dance with the rerendering when the build count changes, and figured it would move things forward. 

humorously, it looks like a future release will move `python-igraph` to `extras` anyway, but hey, so it goes.

since CI is happy (no big surprise) and i've been able to verify it locally on a windows VM, I'll go ahead and merge this, as I'm sure you actually just want to use it, rather than incur future chores... but certainly PR if you'd like to add yourself as a co-maintainer! I'm not a daily user of this package at present, and it's always good to have people that are vested in it continuing to function correctly!

**Pull request merged**
